### ISSUE TITLE
Player Connection Issue with TN

### ISSUE THREAD

**Issue by Phantom139** [PhantomGamesDevelopment/TWM2#12]
Noticed this in my server yesterday when someone tried to join.

For some reason, getAuthInfo() is returning blank on some players when they attempt to connect. I'm not sure if this is related to TN, or an error in the TWM2 code, but I'll leave this here for more investigation.

**Comment by Ragora** [comment]
This is a known TribesNext bug that is rare. Unfortunately isn't really ever going to get fixed at this rate officially, though.

**Comment by Phantom139** [comment]
I see, well if it's a known TN bug then it is not relevant to TWM2. Closing.
